### ISSUE TITLE
Membrane label

### ISSUE THREAD

**Issue by jqyhuang** [kalemaria/pycurv#4]
Hello!

I'm trying to apply pycurv to viral membranes that were segmented using EMAN2, and I was wondering what label I would use for surface generation since the segmentation was not generated in TomosegmemTV and do not contain any labels.

Best,
Judy Huang

**Comment by kalemaria** [comment]
Dear Dr. Huang,

Thanks for using PyCurv! Sorry, I'm not familiar with EMAN2. How does its segmentation output look like, if it does not contain any labels?

Best,
Maria Salfer

**Comment by jqyhuang** [comment]
Hello Maria,

Please call me Judy since I'm a current PhD student!

The segmentation output is a .hdf file which is easily convertible to a .mrc file. The output only contains voxels from the feature of interest, and there is no other component from the tomogram in it. I will attach a screenshot of a membrane segmentation for reference. The purple sections are the membrane. 

Best,

Judy
![image](https://user-images.githubusercontent.com/62765130/93126782-d2305200-f69a-11ea-999a-50f347897be6.png)

**Comment by kalemaria** [comment]
Hello Judy,

sorry, I was not sure. :-D (I'm also still a PhD student.)
It looks like you just have a binary segmentation, which is the simplest case: the membrane voxels probably have value 1 and the background 0. In this case, the label for the surface generation would be 1. But it mights be different depending on how the program stores the data. You could easily check the values range by reading in the image using Python or opening it with some interactive tool like IMOD or Amira. Please let me know if you need help.

Best
Maria

**Comment by jqyhuang** [comment]
Hi Maria, 

Thank you so much for the response! I think the reason I had issues was because my membrane voxels actually don't have binary values, but there is a way to convert the segmentations to a binary range. 

Best,

Judy

**Comment by kalemaria** [comment]
Hi Judy,

Happy to hear that you solved the problem! In case the surface is erroneous using just the membrane segmentation, it would be advantageous to also segment the lumen of the vesicles as a different label and use the compartment surface extraction algorithms.
I'll close this issue, please open a new one if you encounter other problems.

Best
Maria
