### ISSUE TITLE
DeprecationWarning: np.float and np.int are deprecated

### ISSUE THREAD

**Issue by bbarad** [kalemaria/pycurv#9]
Newer versions of numpy don't support calling numpy data types with too low precision - https://numpy.org/doc/stable/release/1.24.0-notes.html#expired-deprecations. Could just pin older numpy versions as a requirement but I think the best approach would be to replace np.int with np.int32 etc where appropriate. I'm happy to prepare a PR to address this.

**Comment by kalemaria** [comment]
Thank you for fixing this! I assume you have run the tests after the change? ;)
